Simulacro

Abrir archivo:

```{r}
library(openxlsx)
fileToRead="https://github.com/PoliticayGobiernoPUCP/EstadisticaPoliticaGobiernoII/raw/master/sesiones/data/IDE_limpio.xlsx"
ide=read.xlsx(fileToRead)
```

Exploración inicial:
```{r, eval=FALSE}
summary(ide)
```


Imputando valores perdidos?
```{r, eval=FALSE}
for(i in 5:ncol(ide[])){  
  MEDIA=mean(ide[,i], na.rm = TRUE) 
  lapop[is.na(ide[,i]), i] <- round(MEDIA,0)
}
```

Cuantos clusters puedo crear?
```{r}
ideS=scale(ide[,-c(1:6)])
row.names(ideS)=ide$provinciaNombre

library(NbClust)
nb <- NbClust(ideS, method = "complete")
```

Si agrupo como me recomiendan, cuantas provincias no se agruparían bien bajo un esquema jerarquico?
```{r}
library(factoextra)
algoritmo="hclust"
cuantosClusters=length(table(nb$Best.partition))
resultadoJ <- eclust(ideS,FUNcluster =algoritmo,
                     k = cuantosClusters,
                     method = "complete",
                     graph = FALSE) 
siluetas=resultadoJ$silinfo$widths
BadCluster=siluetas[siluetas$sil_width<0,]
nrow(BadCluster)
```

Tendremos 3 variables latentes entre todas las observadas?
```{r}
observadas=ide[,-c(1:6)]
matriz=cor(observadas)
library(psych)
KMO(matriz)
cortest.bartlett(matriz, n=nrow(ide))
resultadoPr=principal(matriz,3,rotate="varimax", scores=T)
print(resultadoPr,digits=3,cut = 0.4)
```

